app:
  ui_state:
    window_size:
    - 1400
    - 900
default_profile: cpu
logging:
  backup_count: 5
  console: true
  file: true
  level: INFO
  max_file_size_mb: 10
paths:
  cache: cache
  logs: logs
  models: models
  output: ${OUTPUT_DIR:-output}
  output_det: ${OUTPUT_DET_DIR:-output_det}
  output_rec: ${OUTPUT_REC_DIR:-output_rec}
  temp: temp
  workspaces: workspaces
profiles:
  cpu:
    device:
      type: cpu
    paddleocr:
      cpu_threads: 8
      device: cpu
      enable_mkldnn: false
      lang: th
      max_image_size: 2500
      mkldnn_cache_capacity: 10
      text_det_box_thresh: 0.7
      text_det_unclip_ratio: 1.5
      text_recognition_batch_size: 6
      use_doc_orientation_classify: false
      use_doc_unwarping: false
      use_textline_orientation: true
  gpu:
    device:
      gpu_id: 0
      gpu_mem: 8000
      type: gpu
    paddleocr:
      device: gpu
      enable_mkldnn: false
      lang: th
      max_image_size: 2500
      precision: fp32
      text_det_box_thresh: 0.7
      text_det_unclip_ratio: 1.5
      text_recognition_batch_size: 12
      use_doc_orientation_classify: false
      use_doc_unwarping: false
      use_tensorrt: false
      use_textline_orientation: true
